### PR TITLE
npm@2.13.3

### PR DESCRIPTION
**Pull request by mnquintana**
This bumps npm to the latest version (2.11.2) - part of [an effort to update dependencies.](https://david-dm.org/atom/apm) Let's see if this goes green! :traffic_light:

### CODE REVIEW

**Comment by kevinsawicki** [comment]
Usually I manually test these upgrades as well just to make sure things still work across the network and installing actually packages with dependencies.

**Comment by mnquintana** [comment]
Sure, I'll test this more this afternoon.

**Comment by mnquintana** [comment]
@kevinsawicki Do you want to wait till post-1.0 to update npm?

**Comment by kevinsawicki** [comment]
> Do you want to wait till post-1.0 to update npm?

Yeah, I would, it looks like there were mixed reports of it fixing the windows lag on the other issue and I'd like to look at the npm changelog more closely before bumping it.

**Comment by Stanzilla** [comment]
npm@3 will be the real blessing for Windows anyway. Might just wait until that is final.

**Comment by kevinsawicki** [comment]
@mnquintana want to take this to 2.13.4? I'm fine with this going out now that 1.0 is past us.

**Comment by mnquintana** [comment]
@kevinsawicki Done!

**Pull request merged**
