### PR TITLE
Compatibility With Node v4 and npm v3+

### PR DESCRIPTION
**Pull request by joefitzgerald**
- Revert commit bac0d17
- Explicitly Depend On Coffeelint, For npm v3+

### CODE REVIEW

**Comment by steelbrain** [comment]
:+1:

**Comment by nathansobo** [comment]
Just published a pre-release to try this out again with our infernal internal build system.

**Comment by gjtorikian** [comment]
Any status updates, @nathansobo?

**Comment by nathansobo** [comment]
Blocked on fixing our internal build situation. We're stuck on Node 0.10 on machines we can't readily administer, and that version can't build native modules that will link against Node 4 on Linux and Windows. I'm working to get us on third party providers instead but it's complicated and there's some other stuff going on for me. Hopefully in the next few weeks I can switch us. In the meantime were hoping to get help upgrading Node on Janky.

**Comment by joefitzgerald** [comment]
@nathansobo if you can enable me to do this, I can complete the work of moving to an external provider...

**Comment by nathansobo** [comment]
@joefitzgerald Let me see if I can get a server running this week on a Windows EC2 instance to sign binaries. That prevents us from exposing our signing certificate on AppVeyor and keeps the security team happy. That should clear the last major obstacle and you could take it the rest of the way.

**Comment by neurosnap** [comment]
Any updates on this PR?

**Comment by joefitzgerald** [comment]
This really should be bumped to node 6.

**Pull request closed without merging**
