### PR TITLE
Add ability to use #comments in packages file

### PR DESCRIPTION
**Pull request by danielbayley**
Lines beginning with `#` will be ignored.

Signed-off-by: Daniel Bayley daniel.bayley@me.com

### CODE REVIEW

**Comment by bronson** [comment]
Hi, this sounds like a great idea.  I sure can't speak for the Atom project but, if I was merging it, I'd be interested in seeing some tests.

**Comment by mnquintana** [comment]
Yup, would you mind adding some specs for this to prevent regressions? Thanks!

**Comment by danielbayley** [comment]
Sure, but how I would go about doing that here? All I did was change it from only splitting package names on spaces to extracting only properly formatted `package[-]name`s (leaving anything else, including comments alone.

Is there no existing spec for `@sanitizePackageNames`?

**Comment by jtkiley** [comment]
I'd be really happy to see this. When you have a longish list of packages (e.g. in a dotfiles repository), it's nice to use comments to create sections.

**Comment by cwhy** [comment]
May I ask why is this not merged? Is there anything that I can help to get it merged?

**Comment by danielbayley** [comment]
I’ll try and add specs over the weekend if I can find time.

**Comment by jtkiley** [comment]
Any idea what happened to this? It would still be really nice, and it doesn't work on the most current release.

**Pull request closed without merging**
