### PR TITLE
add --enabled and --disabled flags to `apm list`

### PR DESCRIPTION
**Pull request by bronson**
As requested in https://github.com/atom/apm/pull/400#issuecomment-253913575

This is based on top of #617 so that PR should be merged first.

### CODE REVIEW

**Comment by bronson** [comment]
I'm curious why --enabled was recently merged from https://github.com/atom/apm/pull/729

Will this PR ever be reviewed?

**Comment by Ben3eeE** [comment]
@bronson Sorry for the delay here - we've since tweaked our process a bit to better track issues and PRs so hopefully things don't fall through the cracks like they did here.

Can you fix the merge conflicts here? I have added this PR to the triage board.

**Comment by damieng** [comment]
Any interest in getting the merge conflicts addressed so we can get this in?

**Comment by bronson** [comment]
Yes.  Thanks for keeping this in mind.  Last week sure went quick, I'll do it soon.

**Comment by bronson** [comment]
@damieng finally found the time.  Updated now.

**Comment by BinaryMuse** [comment]
This looks good. Thanks for the contribution!

**Pull request merged**
