### PR TITLE
Add UI theme to templates

### PR DESCRIPTION
**Pull request by simurai**
:warning: WIP :warning: 

This PR adds a UI theme to the templates. It's pretty basic and only has styles to "make it work".

screen shot 2015-07-23 at 12 10 05 pm

### Motivation

It came up in this [discussion](https://discuss.atom.io/t/docs-for-creating-an-interface-theme/17254) and later in a chat with @mnquintana. Basically have a simpler starter UI theme without any fancy stuff like in the One themes, but with good inline documentation. Should make it easier to get started when creating your own theme on top of a "blueprint" instead of trying to modify an existing theme that might be hard to understand. Forking a community theme is still encouraged, of course.

Also, makes it more complete, having a UI theme next to the Syntax theme.

### TODO

- [x] Add initial theme
- [x] Add inline documentation
- [x] Add option to the Package Generator https://github.com/atom/package-generator/pull/31
- [ ] Make it work from the CL (`apm init`), currently testing on the `sm-ui-theme-cl` branch
- [ ] Add specs

### CODE REVIEW

**Comment by simurai** [comment]
Tried to make it work with the Package Generator, but got stuck. It only opens the root directory and not the `theme-ui` template. Probably got some path/name wrong.

If somebody wants to take over, that would be awesome.

**Comment by simurai** [comment]
Ok, I tried to take another stab at this:

1. Added an option to the package generator: https://github.com/atom/package-generator/pull/31. It didn't work (it just opened my default directory), but I figured it's because apm didn't have an `init` option for a UI theme.
2. So then I made another branch `sm-ui-theme-cl` on top of this one to test the `apm init`: https://github.com/atom/apm/commit/75ec98e6ffa6fc00e5dcb2fe969f889283c0ccab

__Question__: How do I test `apm init` after making changes to `apm` itself? I guess I can't just `apm link -d`. I tried the steps under [Building](https://github.com/atom/apm#building), but when running `grunt`, I get `-bash: grunt: command not found`.

/cc @atom/feedback

**Comment by thedaniel** [comment]
@simurai if you want to test apm on the command line, you can just build it and run it with an absolute path, like `~/git/apm/bin/apm init`

If you need to test it within atom I suppose you could change this line https://github.com/atom/atom/blob/master/src/package-manager.coffee#L115 and run in dev mode, though there's probably a better way.

**Comment by simurai** [comment]
@thedaniel Thanks! After building I tried to run apm with the absolute path, but I get this:

```
$ /Users/simBook/Sir/apm/bin/apm -h

dyld: lazy symbol binding failed: Symbol not found: _node_module_register
  Referenced from: /Users/simBook/Sir/apm/node_modules/keytar/build/Release/keytar.node
  Expected in: dynamic lookup

dyld: Symbol not found: _node_module_register
  Referenced from: /Users/simBook/Sir/apm/node_modules/keytar/build/Release/keytar.node
  Expected in: dynamic lookup

/Users/simBook/Sir/apm/bin/apm: line 28: 28976 Trace/BPT trap: 5       "$binDir/$nodeBin" --harmony_collections "$binDir/../lib/cli.js" "$@"
```

Hmm.. this might be a bit over my head. If somebody wants to take over, feel free. :grin: But priority is probably not that high for this.

I could also first put the template up on https://github.com/atom-community just to see if there is some demand.

**Comment by thedaniel** [comment]
@simurai I get the same errors when building following the README. I haven't worked on apm in a minute, but I'll try to figure out what's causing this and update the docs.

**Comment by thedaniel** [comment]
@simurai looks like you just can't build apm with node 0.12 right now, you have to rm -rf your node_modules and use nvm or similar to build it with 0.10. Hopefully we'll update to node 4+ soon, but for now this works. LMK if you need more detailed instructions.

**Comment by simurai** [comment]
Closing this (unless somebody wants to continue).

There is a [UI theme template](https://github.com/atom-community/ui-theme-template) that can be forked as an alternative to this.

**Pull request closed without merging**
