### PR TITLE
Develop git url

### PR DESCRIPTION
**Pull request by UziTech**
### Description of the Change
allow `apm develop` to accept a git url instead of a package name

```
      Usage: apm develop <package_name> [<directory>]
             apm develop <git_remote> [<directory>]
             apm develop <github_username>/<github_project> [<directory>]
             apm dev (with any of the previous argument usage)
```

### Benefits

can develop a fork of a package

### Possible Drawbacks

none

### Applicable Issues

#739

### CODE REVIEW

**Comment by UziTech** [comment]
Any feedback on this?

**Comment by iolsen** [comment]
Hey thanks for the contribution, @UziTech. Can you add to the body of this PR some details that would be useful in documentation? E.g. what are the behavioral differences from develop <package name>. What happens when you apm publish? (Presumably the package.json needs to be well-formatted for that to work.)

**Comment by iolsen** [comment]
Upon further review with the maintainer team this isn't a change we're ready to accept and support. Thanks for your contribution!

**Comment by UziTech** [comment]
Is there a reason why `apm develop` shouldn't be used with a git url?

**Comment by UziTech** [comment]
I'm curious how this would be any harder to maintain than #518

**Comment by weilaihaojiubujian** [comment]
I'm curious how this would be any harder to maintain

**Pull request closed without merging**
