### PR TITLE
Update links to docs in templates

### PR DESCRIPTION
**Pull request by izuzak**

### CODE REVIEW

**Comment by izuzak** [comment]
@kevinsawicki If I want to merge this and bump the version of apm in [package.json](https://github.com/atom/apm/blob/master/package.json), I would just create a tag for it and update package.json manually? And then update https://github.com/atom/atom/blob/master/apm/package.json manually?

**Comment by kevinsawicki** [comment]
Yup, my release flow is:

```
npm version minor
git push origin master v0.XXX.0
npm publish
```

Then update the version in the `apm/package.json` file in atom/atom

**Comment by izuzak** [comment]
Great, thanks for those instructions

**Comment by izuzak** [comment]
Ahhh, I don't have authorization to publish to `npm`. Can you run that `npm publish` for me, @kevinsawicki, or give me the :key: to do it myself?

**Comment by kevinsawicki** [comment]
> Ahhh, I don't have authorization to publish to npm

Sorry about that, you should have access now.

**Comment by izuzak** [comment]
:bow:

**Pull request merged**
