### PR TITLE
Bump year in template automatically

### PR DESCRIPTION
**Pull request by hokaccha**
We need to update year in template every year. It should be automated :smiley_cat:

### CODE REVIEW

**Comment by lee-dohm** [comment]
Sorry about the label spam. Was juggling processes around.

**Comment by damieng** [comment]
Hi, can you resolve the merge conflicts?

**Comment by hokaccha** [comment]
@damieng resolved.

**Comment by thomasjo** [comment]
@hokaccha Thanks for this! Apologies for the delay in merging this 🙇

**Pull request merged**
