### PR TITLE
Use ATOM_ACCESS_TOKEN On Install If Set

### PR DESCRIPTION
**Pull request by joefitzgerald**
- Fixes https://github.com/atom/ci/issues/39

/cc @lee-dohm @thedaniel

### CODE REVIEW

**Comment by thomasjo** [comment]
Looks good to me!

**Comment by joshaber** [comment]
I mentioned this in chat, but for posterity: I'm not sure this is the change we need, unless I'm misunderstanding this (which is entirely possible!).

The rate limit message is coming from github.com's API, not atom.io itself. It's atom.io's usage of GitHub's API that's being rate-limited.

It seems possible this is related to a change I made to atom.io earlier this week, so I've reverted it. Lemme know if you still see rate limiting.

**Comment by joshaber** [comment]
(If the above is right, we should also revert https://github.com/atom/ci/pull/40.)

**Comment by joefitzgerald** [comment]
@joshaber 's theory was correct. This is now resolved.

**Pull request closed without merging**
